# Service definitions
parameters:

services:
    aureka.disqus.twig_extension:
        class: Aureka\DisqusBundle\Twig\AurekaDisqusExtension
        arguments: ['%aureka_disqus.short_name%']
        tags:
            - { name: twig.extension }
