# Service definitions
parameters:

services:
    aureka.disqus.twig_extension:
        class: Aureka\DisqusBundle\Twig\AurekaDisqusExtension
        arguments: ['short_name']
        tags:
            - { name: twig.extension }
